data_dir = "/var/lib/vector"

[api]
    enabled = true
    address = "0.0.0.0:8686"

# 应用访问日志
[sources.app_access_logs]
type = "file"
include = ["/var/log/exported/access-*"]
multiline.mode = "halt_before"
multiline.start_pattern = '^\{'
multiline.condition_pattern = '\}'
encoding.charset = "utf-8"
multiline.timeout_ms = 1000

[transforms.parse_access_logs]
type = "remap"
inputs = ["app_access_logs"]
source = '''
. = parse_json!(.message)
.timestamp = now()
.host = get_hostname!()
'''

[sinks.cloudwatch_access_logs]
type = "aws_cloudwatch_logs"
inputs = ["parse_access_logs"]
region = "ap-northeast-1"
group_name = "/ecs/laravel-app/access-logs"
stream_name = "{{ host }}"
encoding.codec = "json"