data_dir = "/var/lib/vector"

[api]
    enabled = true
    address = "0.0.0.0:8686"

# 应用访问日志
[sources.app_access_logs]
type = "file"
include = ["/var/log/exported/access-*"]
encoding.charset = "utf-8"

[transforms.parse_access_logs]
type = "remap"
inputs = ["app_access_logs"]
source = '''
# 使用正则表达式提取 JSON 部分
if match!(.message, r'(?P<json>\{.*\})') {
    . = parse_json!(.regex.json)
    .timestamp = now()
    .host = get_hostname!()
} else {
    # 如果没有匹配到 JSON，记录原始日志
    log(level: "warn", value: "Could not extract JSON from log message. Raw message: " + to_string!(.message));
    . = {"raw_log": .message}
}
'''

[sinks.cloudwatch_access_logs]
type = "aws_cloudwatch_logs"
inputs = ["parse_access_logs"]
region = "ap-northeast-1"
group_name = "/ecs/laravel-app/access-logs"
stream_name = "{{ host }}"
encoding.codec = "json"