data_dir = "/var/lib/vector"

[sources.app_access_logs]
type = "file"
include = ["/var/log/exported/access-*"]
encoding.charset = "utf-8"

[transforms.parse_access_logs]
type = "remap"
inputs = ["app_access_logs"]
source = '''
# 提取 JSON 字符串
parsed = parse_regex!(.message, r'\[(?P<log_time>[^\]]+)\] local\.INFO: (?P<json_content>\{.*\})')

# 解析提取出的 JSON
if exists(parsed.json_content) {
    json_data = parse_json!(parsed.json_content)
    
    # 重构事件
    . = {
        "timestamp": json_data.timestamp,
        "aws_trace_id": json_data."x-amzn-trace-id",
        "duration_ms": json_data.duration_ms,
        "method": json_data.method,
        "url": json_data.url,
        "ip": json_data.ip,
        "status_code": json_data.status_code,
        "user_agent": json_data.user_agent,
        "host": .host,
        "file": .file,
        "source_type": .source_type
    }
}
'''

[sinks.cloudwatch_access_logs]
type = "aws_cloudwatch_logs"
inputs = ["parse_access_logs"]
region = "ap-northeast-1"
group_name = "/ecs/poper-php-test/vector-logs"
stream_name = "{{ host }}"
encoding.codec = "json"