data_dir = "/var/lib/vector"

[api]
    enabled = true
    bind= "0.0.0.0:8686"

[sources.access_logs]
type = "file"
include = ["/var/log/exported/access-*"]  # 应用程序容器中的日志路径
multiline.mode = "halt_before"
multiline.start_pattern = '^{'
multiline.condition_pattern = '}'
format = "json"

[sinks.cloudwatch_access_logs]
type = "aws_cloudwatch_logs"
inputs = ["access_logs"]
region = "ap-northeast-1"
log_group_name = "/ecs/php-poper-vector-logs"
log_stream_name = "{{ host }}/vector-log"